name: (Test) Dev

on:
  pull_request:
    branches: [master]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      client: ${{ steps.filter.outputs.client }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server: ['server/**']
            client: ['client/**']

  setup:
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install

  server:
    runs-on: ubuntu-latest
    needs: [detect-changes, setup]
    if: ${{ needs.detect-changes.outputs.server == 'true' }}
    steps:
      - name: Build Server
        run: pnpm --filter server run build

  client:
    runs-on: ubuntu-latest
    needs: [detect-changes, setup]
    if: ${{ needs.detect-changes.outputs.client == 'true' }}
    steps:
      - name: Build Client
        run: pnpm --filter client run build
