name: (Test) Dev

on:
  pull_request:
    branches: [master]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      client: ${{ steps.filter.outputs.client }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server: ['server/**']
            client: ['client/**']

  process:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.server == 'true' || needs.detect-changes.outputs.client == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Server
        if: ${{ needs.detect-changes.outputs.server == 'true' }}
        run: |

          # install dependencies
          pnpm --filter ./server install

          # build the server
          pnpm --filter ./server run build

      - name: Build Client
        if: ${{ needs.detect-changes.outputs.client == 'true' }}
        run: |

          # install dependencies
          pnpm --filter ./client install

          # build the client
          pnpm --filter ./client run build
