name: (Test) Production

on:
  push:
    branches: [master]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      client: ${{ steps.filter.outputs.client }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server: ['server/**']
            client: ['client/**']

  process:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Log Node & OS versions
        run: |
          node -v
          cat /etc/os-release

      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # server deployment
      - name: Build & Deploy Server
        if: ${{ needs.detect-changes.outputs.server == 'true' }}
        run: |

          # install dependencies
          pnpm --filter ./server install

          # build the server
          pnpm --filter ./server run build

          # install Heroku CLI
          curl https://cli-assets.heroku.com/install.sh | sh

      - uses: akhileshns/heroku-deploy@v3.14.15
        if: ${{ needs.detect-changes.outputs.server == 'true' }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.EMAIL }}
          branch: "master"
          appdir: "server"
          dontautocreate: true

      # build and deploy client to vercel
      - name: Build & Deploy Client
        if: ${{ needs.detect-changes.outputs.client == 'true' }}
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |

          # install dependencies
          pnpm --filter ./client install

          # build the client
          pnpm --filter ./client run build

          # trigger Vercel deploy hook
          curl -X POST $VERCEL_DEPLOY_HOOK
